MeetCIT/MeetCIT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('', include('cal.urls')),
    path('admin/', admin.site.urls),
]

MeetCIT/cal/urls.py
from django.urls import re_path, path
from .views import booksuccess, index, CalendarView, event, event_edit, catalogue, profile, cancelsuccess, cancelhostsuccess, SearchResultsView

app_name = 'cal'
urlpatterns = [
    re_path(r'^calendar/$', CalendarView.as_view(), name='calendar'),
    re_path(r'^event/new/$', event, name='event_new'),
    re_path(r'^event/edit/(?P<event_id>\d+)/$',
            event_edit, name='event_edit'),
    path('', index, name='homepage'),
    re_path(r'^booksuccess/(?P<event_id>\d+)/$',
            booksuccess, name='booksuccess'),
    path('catalogue/', catalogue, name='catalogue'),
    path('profile/', profile, name='profile'),
    re_path(r'^cancelsuccess/(?P<event_id>\d+)/$',
            cancelsuccess, name='cancelsuccess'),
    re_path(r'^cancelhostsuccess/(?P<event_id>\d+)/$',
            cancelhostsuccess, name='cancelhostsuccess'),
    path('search_results/', SearchResultsView.as_view(), name='search_results')
]

MeetCIT/users/urls.py
from django.urls import path, include, re_path
from users.views import register

app_name = 'users'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

MeetCIT/cal/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Event(models.Model):
    host = models.CharField(max_length=200)
    mentee = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, null=True, blank=True)
    zoom_link = models.TextField()
    start_time = models.DateTimeField('start time')
    end_time = models.DateTimeField('end time')
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.host

    def __str__(self):
        return self.zoom_link

    def __datetime__(self):
        return self.start_time

    def __datetime__(self):
        return self.end_time

    def __bool__(self):
        return self.available

    def is_available(self) -> bool:
        return self.start_time > timezone.now() and self.available

    def has_started(self):
        return self.start_time <= timezone.now() <= self.end_time

    def has_ended(self):
        return self.end_time < timezone.now()

    class Meta:
        permissions = (
            ('can_edit', 'Can edit the event'),
            ('cannot_book', 'Cannot book the event')
        )

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        title = self.host + " (BOOKED!)"
        title_expired = self.host + " (EXPIRED!)"
        if self.is_available():
            return f'<a href="{url}"> {self.host} </a>'
        else:
            if self.mentee == None:
                return f'<a href="{url}"> {title_expired} </a>'
            else:
                return f'<a href="{url}"> {title} </a>'

MeetCIT/cal/forms.py
from django.forms import ModelForm, DateInput
from django.utils import timezone
from cal.models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ['host', 'zoom_link', 'start_time', 'end_time']

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['host'].disabled = (True)

    def clean(self):
        super(EventForm, self).clean()

        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')

        if (start_time > end_time):
            self._errors['start_time'] = self.error_class(
                ['Start time cannot be later than end time!'])
        if (start_time <= timezone.now()):
            self._errors['start_time'] = self.error_class(
                ['Start time cannot be earlier than current time!'])
        if (end_time <= timezone.now()):
            self._errors['end_time'] = self.error_class(
                ['End time cannot be earlier than current time!'])

        return self.cleaned_data

MeetCIT/cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from guardian.shortcuts import assign_perm
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm


def index(request):
    return render(request, 'homepage/index.html')


class SearchResultsView(ListView):
    model = Event
    template_name = 'homepage/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        cur_user = User.objects.get(pk=self.request.user.id)
        event_list = Event.objects.filter(host=query).order_by('start_time').exclude(
            available=False).exclude(start_time__lte=timezone.now()).exclude(host=cur_user)
        return event_list


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def catalogue(request):
    if request.user.is_authenticated:
        cur_user = User.objects.get(pk=request.user.id)
        earliest_slots_list = Event.objects.order_by(
            'start_time').exclude(host=cur_user).exclude(available=False).exclude(start_time__lte=timezone.now())
        context = {'earliest_slots_list': earliest_slots_list}
        return render(request, 'homepage/catalogue.html', context)
    else:
        earliest_slots_list = Event.objects.order_by(
            'start_time').exclude(available=False).exclude(start_time__lte=timezone.now())
        context = {'earliest_slots_list': earliest_slots_list}
        return render(request, 'homepage/catalogue.html', context)


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


@login_required
def event(request, event_id=None):
    cur_user = User.objects.get(pk=request.user.id)
    initial_data = {
        'host': cur_user
    }

    instance = Event()

    form = EventForm(request.POST or None,
                     instance=instance, initial=initial_data)
    if request.POST and form.is_valid():

        cur_event = form.save()
        # assign permission to the author
        assign_perm('cannot_book', cur_user, cur_event)
        assign_perm('can_edit', cur_user, cur_event)
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})


@login_required
def event_edit(request, event_id=None):
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        if request.user.has_perm('cal.can_edit', instance):
            cur_user = User.objects.get(pk=request.user.id)
            initial_data = {
                'host': cur_user,
                'zoom_link': instance.zoom_link,
                'start_time': instance.start_time,
                'end_time': instance.end_time,
                'event_id': instance.pk,
            }

            form = EventForm(request.POST or None,
                             instance=instance, initial=initial_data)
            if request.POST and form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('cal:calendar'))
            return render(request, 'cal/event_edit.html', {'form': form, 'instance': initial_data})
        else:
            cur_user = User.objects.get(pk=request.user.id)
            can_cancel = (cur_user == instance.mentee)
            context = {
                'event_id': instance.pk,
                'host': instance.host,
                'zoom_link': instance.zoom_link,
                'start_time': instance.start_time,
                'end_time': instance.end_time,
                'is_available': instance.is_available(),
                'can_cancel': can_cancel,
            }
            print(instance.is_available())
            print(timezone.now())
            return render(request, 'cal/event_view.html', context)


@login_required
def booksuccess(request, event_id):
    cur_user = User.objects.get(pk=request.user.id)
    instance = get_object_or_404(Event, pk=event_id)
    instance.available = False
    instance.mentee = cur_user
    instance.save()
    context = {
        'event_id': instance.pk,
        'host': instance.host,
        'zoom_link': instance.zoom_link,
        'start_time': instance.start_time,
        'end_time': instance.end_time,
        'is_available': instance.is_available(),
    }
    return render(request, 'cal/booksuccess.html', context)


@login_required
def profile(request):
    cur_user = User.objects.get(pk=request.user.id)

    host_event_expired = Event.objects.filter(host=cur_user).order_by(
        'start_time').exclude(start_time__gte=timezone.now())
    host_event_upcoming = Event.objects.filter(host=cur_user).order_by(
        'start_time').exclude(start_time__lte=timezone.now())

    user_event_expired = Event.objects.filter(mentee=cur_user).order_by(
        'start_time').exclude(start_time__gte=timezone.now())
    user_event_upcoming = Event.objects.filter(mentee=cur_user).order_by(
        'start_time').exclude(start_time__lte=timezone.now())

    context = {'host_event_expired': host_event_expired,
               'host_event_upcoming': host_event_upcoming,
               'user_event_expired': user_event_expired,
               'user_event_upcoming': user_event_upcoming,
               }

    return render(request, 'cal/profile.html', context)


@login_required
def cancelsuccess(request, event_id):
    instance = get_object_or_404(Event, pk=event_id)
    instance.available = True
    instance.mentee = None
    instance.save()
    context = {
        'event_id': instance.pk,
        'host': instance.host,
        'zoom_link': instance.zoom_link,
        'start_time': instance.start_time,
        'end_time': instance.end_time,
        'is_available': instance.is_available(),
    }
    return render(request, 'cal/cancelsuccess.html', context)


@login_required
def cancelhostsuccess(request, event_id):
    instance = get_object_or_404(Event, pk=event_id)
    context = {
        'host': instance.host,
        'mentee': instance.mentee,
        'start_time': instance.start_time,
    }
    instance.delete()
    return render(request, 'cal/cancelhostsuccess.html', context)

MeetCIT/cal/templates/cal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
      integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'cal/css/styles.css' %}"
    />
    <link href='https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic|Montserrat:400,700|Cardo:400italic|Advent+Pro:100' rel='stylesheet' type='text/css'>
    <title>MeetCIT</title>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a
        class="navbar-brand"
        href="{% url 'cal:homepage' %}"
        style="color: #33cccc"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="25"
          height="25"
          fill="currentColor"
          class="bi bi-calendar2-check-fill"
          viewBox="0 0 16 16"
        >
          <path
            fill="#33CCCC"
            d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zm-2.6 5.854a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"
          />
        </svg>MeetCIT
      </a>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-item nav-link" href="{% url 'cal:calendar' %}">Calendar</a></li>
          <li class="nav-item"><a class="nav-item nav-link" href="{% url 'cal:catalogue' %}">Catalogue</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item mr-3 input-group w-50">
            <form action="{% url 'cal:search_results' %}" method="get" class="d-flex">
              <span class="input-group-text" id="basic-addon1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg></span>
              <input aria-describedby="basic-addon1" name="q" type="text" placeholder="I want to meet ... " aria-label="Search" class="form-control me-2">
            </form>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'cal:profile' %}"
              >Profile</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'users:logout' %}"
              >Logout</a
            >
          </li>
          {% else %}
          <li>
            <a class="nav-item nav-link" href="{% url 'users:login' %}"
              >Login</a
            >
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'users:register' %}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <h1 class="title">{% block title %}{% endblock %}</h1>

    {% block content %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    {% block script %} {% endblock %}
  </body>
</html>

MeetCIT/cal/templates/cal/booksuccess.html
{% extends 'cal/base.html' %}

{% block content %}
<div class='ml-3'>
    <p>
        Congratulations!
        Your appointment with {{ host }} at {{ start_time }} is successful!
    </p>
</div>
{% endblock %}

MeetCIT/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"><svg xmlns="http://www.w3.org/2000/svg"
      width="20" height="20" fill="currentColor" class="bi bi-caret-left-fill" viewBox="0 0 16 16">
      <path
        d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z" />
    </svg> Previous Month </a>
  <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month <svg
      xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-caret-right-fill"
      viewBox="0 0 16 16">
      <path
        d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
    </svg></a>
  <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Host an Appointment! <svg
      xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-people-fill"
      viewBox="0 0 16 16">
      <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
      <path fill-rule="evenodd"
        d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
      <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
    </svg></a>
</div>

{{ calendar }}
{% endblock %}

MeetCIT/cal/templates/cal/cancelhostsuccess.html
{% extends 'cal/base.html' %}

{% block content %}
{% if mentee %}
<div class='ml-3'>
    <p>
        Your host appointment with {{ mentee }} at {{ start_time }} has been successfully canceled.
    </p>
</div>
{% else %}
<div class='ml-3'>
    <p>
        Your host appointment at {{ start_time }} has been successfully canceled.
    </p>
</div>
{% endif %}
{% endblock %}

MeetCIT/cal/templates/cal/cancelsuccess.html
{% extends 'cal/base.html' %}

{% block content %}
<div class='ml-3'>
    <p>
        Your appointment with {{ host }} at {{ start_time }} has been successfully canceled.
    </p>
</div>
{% endblock %}

MeetCIT/cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

MeetCIT/cal/templates/cal/event_edit.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    {{ field.label }} <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    <table class="form form-table" align="center">
        {{ form }}
    </table>
        <div class="row" style="margin-left:200px">
            <div class="col"><a class="btn btn-info right" href="{% url 'cal:cancelhostsuccess' instance.event_id %}"> Cancel Appointment</a></div>
            <div class="col"><button type="submit" class="btn btn-info"> Submit </button></div>
        </div>
</form>

{% endblock %}

MeetCIT/cal/templates/cal/event_view.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}

<div align="center">
  <div class="card mt-4 w-50 text-center" style="width: 18rem;">
    <div class="card-body">
      <p class="card-title title">Host name: {{host}}</p>
      <p class="card-text text-muted">Start time: {{start_time}}</p>
      <p class="card-text text-muted">End time: {{end_time}}</p>
      {% if is_available %}
      <p class="card-text text-muted">Available: Yes</p>
      <form method="post">
        <a class="btn btn-info" href="{% url 'cal:booksuccess' event_id %}"> BOOK ME! </a>
      </form>
      {% else %}
      <p class="card-text text-muted">Available: No</p>

      {% if can_cancel %}
      <a class="btn btn-info" href="{% url 'cal:cancelsuccess' event_id %}"> Cancel Appointment </a>
      {% endif %}

      {% endif %}
    </div>
  </div>
</div>



{% endblock %}

MeetCIT/cal/templates/cal/profile.html
{% extends 'cal/base.html' %}

{% block content %}
<h1 class='col ml-5'>
    Welcome back, {{user}}!
</h1>

<div class="row ml-5 mt-3">
    <div class="col-sm-6">
        {% if host_event_upcoming %}
        <h2>Upcoming host appointments:</h2>
        {% for query in host_event_upcoming %}
        {% if query.mentee %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Attendee name: {{query.mentee}}</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
                <p class="card-text">Zoom link: {{query.zoom_link}}</p>
                <a class="btn btn-info" href="{% url 'cal:cancelhostsuccess' query.pk %}"> Cancel Appointment </a>
            </div>
        </div>
        {% else %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Appointment not booked yet!</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
                <a class="btn btn-info" href="{% url 'cal:cancelhostsuccess' query.pk %}"> Cancel Appointment </a>
            </div>
        </div>
        {% endif %}
        {% endfor %}


        {% else %}
        <h2>No upcoming host appointment. Go <a href="{% url 'cal:event_new' %}">host an appointment</a> now!
        </h2>

        {% endif %}

        {% if host_event_expired %}
        <h2 class='mt-3'>Past host appointments:</h2>
        {% for query in host_event_expired %}
        {% if query.mentee %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Attendee name: {{query.mentee}}</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
            </div>
        </div>
        {% else %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Appointment was not booked!</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>


    <div class="col-sm-6">
        {% if user_event_upcoming %}
        <h2>Upcoming appointments:</h2>
        {% for query in user_event_upcoming %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Host name: {{query.host}}</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
                <p class="card-text">Zoom link: {{query.zoom_link}}</p>
                <a class="btn btn-info" href="{% url 'cal:cancelsuccess' query.pk %}"> Cancel Appointment </a>
            </div>
        </div>
        {% endfor %}

        {% else %}
        <h2>No upcoming appointment. Go <a href="{% url 'cal:catalogue' %}">book an appointment</a> now!
        </h2>

        {% endif %}

        {% if user_event_expired %}
        <h2 class='mt-3'>Past appointments:</h2>
        {% for query in user_event_expired %}
        <div class="card mt-4 w-50 text-center" style="width: 18rem;">
            <div class="card-body">
                <p class="card-title title">Host name: {{query.host}}</p>
                <p class="card-text text-muted">Start time: {{query.start_time}}</p>
                <p class="card-text text-muted">End time: {{query.end_time}}</p>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
</div>

{% endblock %}